### ISSUE TITLE
Inspiration from HBLL & MyMap design

### ISSUE THREAD

**Issue by alexkolson** [byu-oit-appdev/byu-polymer-theme#2]
The [HBLL app](http://lib.byu.edu/) design is awesome. Responsive, snappy, and good looking. The markup is clean to boot. I also really like the new look and feel for mymap. It's not responsive but it sure is clean and nice. Incorporating some of the elements of these designs would be cool.

**Comment by ThatJoeMoore** [comment]
The problem is that I'm not trying to come up with a new look and feel, I'm trying to implement the current official look and feel (at https://github.com/byuweb/HTML-Templates).  As much as I like the Library's site, it actually goes against the agreed-upon university-wide look and feel.

However, the MyMap pages do use a variant of the official theme.  I'm thinking I'd like to implement a tab bar that's similar to theirs, as well as a standard person lookup and a few other things.  However, those might be better implemented as separate element bundles.

If you have specific recommendations for things we could use from each, though, I'd love to hear them.

**Comment by alexkolson** [comment]
Now I better understand what the goal is and you've captured the essence of what I was saying, especially with #3, so I'm going to close this. Thanks!
