### ISSUE TITLE
Design is off-centered on both mobile and desktop

### ISSUE THREAD

**Issue by alexkolson** [byu-oit-appdev/byu-polymer-theme#7]
The design is slightly off-center down and to the right:

![image](https://cloud.githubusercontent.com/assets/281637/12283672/d0e6e6ec-b965-11e5-9e22-3dade9797380.png)
![image](https://cloud.githubusercontent.com/assets/281637/12283682/def3e172-b965-11e5-8674-7145b944c555.png)

**Comment by ThatJoeMoore** [comment]
That's because <body> comes with margins and/or padding by default. You need to zero those out, or use the Polymer fullbleed features described at https://elements.polymer-project.org/guides/flex-layout#full-bleed-lt-body-gt- .  

I'm going to keep this open so that I remember to document this behavior.

**Comment by alexkolson** [comment]
Sounds good! Thanks!

**Comment by ThatJoeMoore** [comment]
Fixed by commit 9b879b5 .  It is now automatic - if you use byu-page on your page, it will grab the body element and kill those nasty margins.
